### ISSUE TITLE
Thermostat unreachable - Network timeout

### ISSUE THREAD

**Issue by litinoveweedle** [algirdasc/hass-floureon#7] opened 2020-10-12 10:59 UTC
Unfortunately [this](https://github.com/algirdasc/hass-floureon/issues/5) was closed without original issue resolution.

Even with upgraded python-broadlink to 0.15.0 Floureon thermostat connected to HA secondary network (not primary NIC) is still unreachable. As original issue is closed I am opening this one.

I think [this](https://github.com/mjg59/python-broadlink/pull/427) (especially point 3.) will have to be considered in Floureon integration to work correctly as well.

currently I am getting:
`2020-10-11 19:32:36 WARNING (MainThread) [custom_components.floureon] Thermostat 192.168.3.57 read_status error: [Errno -4000] Network timeout
2020-10-11 19:33:36 WARNING (MainThread) [custom_components.floureon] Thermostat 192.168.3.57 read_status error: [Errno -4000] Network timeout
2020-10-11 19:34:36 WARNING (MainThread) [custom_components.floureon] Thermostat 192.168.3.57 read_status error: [Errno -4000] Network timeout
2020-10-11 19:35:36 WARNING (MainThread) [custom_components.floureon] Thermostat 192.168.3.57 read_status error: [Errno -4000] Network timeout
2020-10-11 19:36:36 WARNING (MainThread) [custom_components.floureon] Thermostat 192.168.3.57 read_status error: [Errno -4000] Network timeout
2020-10-11 19:37:36 WARNING (MainThread) [custom_components.floureon] Thermostat 192.168.3.57 read_status error: [Errno -4000] Network timeout`

_Originally posted by @litinoveweedle in https://github.com/algirdasc/hass-floureon/issues/5#issuecomment-706743814_

**Comment by algirdasc** [comment] 2020-10-12 11:47
Duplicate of #5

**Closed by algirdasc** 2020-10-12 11:47 UTC
